In [2]:
import pandas as pd
import numpy as np

Alcaldes 2018

In [3]:
my_content = pd.read_csv('NL_AYUN_2018.csv')

In [4]:
group = my_content.groupby('MUNICIPIO')

In [5]:
NL_AYUN_2018 = group.sum()

In [6]:
NL_AYUN_2018.head()

,ID_ESTADO,ID_MUNICIPIO,SECCION,ID_CASILLA,EXT_CONTIGUA,UBICACION_CASILLA,TIPO_ACTA,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,TOTAL_REP_PARTIDO_CI_VOTARON,...,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,OBSERVACIONES,CONTABILIZADA,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,76,4,6,6,2.0,8,20,0,0,0,...,1734,2288,78,0.0,4,0.0,0.0,0.0,0.0,0.0
Agualeguas,190,20,66,11,1.0,19,50,0,0,0,...,2938,3965,181,0.0,10,0.0,0.0,0.0,0.0,0.0
Allende,874,184,1231,99,53.0,60,230,0,0,0,...,14358,27284,877,0.0,46,0.0,0.0,0.0,0.0,0.0
Anahuac,513,135,1226,42,15.0,37,135,0,0,0,...,9218,14525,494,0.0,27,0.0,0.0,0.0,0.0,0.0
Apodaca,13072,4128,812254,2836,886.0,727,3444,0,0,0,...,219581,403094,9977,0.0,688,0.0,0.0,0.0,0.0,0.0

In [7]:
NL_AYUN_2018.drop(['ID_ESTADO','ID_MUNICIPIO','SECCION','ID_CASILLA','EXT_CONTIGUA','UBICACION_CASILLA','TIPO_ACTA','SHA','FECHA_HORA_ACOPIO','FECHA_HORA_VERIFICACION','ORIGEN','DIGITALIZACION'

], axis = 1, inplace= True)

In [8]:
NL_AYUN_2018.head()

,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,TOTAL_REP_PARTIDO_CI_VOTARON,TOTAL_VOTOS_SACADOS,PAN,PRI,PRD,PT,PVEM,MC,...,CI_5,CI_6,CNR,Votos Anulados,TOTAL_VOTOS_ASENTADO,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,OBSERVACIONES,CONTABILIZADA
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,0,0,0,0,119,440,31,33,18,436,...,0,0,1,54,0.0,1734,2288,78,0.0,4
Agualeguas,0,0,0,0,1216,1074,0,0,1,601,...,0,0,1,33,0.0,2938,3965,181,0.0,10
Allende,0,0,0,0,4633,4764,0,431,90,2039,...,0,0,1,376,0.0,14358,27284,877,0.0,46
Anahuac,0,0,0,0,1582,3280,32,62,56,851,...,0,0,0,287,0.0,9218,14525,494,0.0,27
Apodaca,0,0,0,0,50330,69818,1480,5883,5958,10756,...,0,0,64,4059,0.0,219581,403094,9977,0.0,688

In [9]:
NL_AYUN_2018.to_csv('final_NL_AYUN_2018.csv')

Alcaldes 2021

In [10]:
my_content_2021 = pd.read_csv('NL_AYUN_2021.csv')

In [11]:
group = my_content.groupby('MUNICIPIO')

In [12]:
NL_AYUN_2021 = group.sum()

In [13]:
NL_AYUN_2021.head()

,ID_ESTADO,ID_MUNICIPIO,SECCION,ID_CASILLA,EXT_CONTIGUA,UBICACION_CASILLA,TIPO_ACTA,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,TOTAL_REP_PARTIDO_CI_VOTARON,...,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,OBSERVACIONES,CONTABILIZADA,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,76,4,6,6,2.0,8,20,0,0,0,...,1734,2288,78,0.0,4,0.0,0.0,0.0,0.0,0.0
Agualeguas,190,20,66,11,1.0,19,50,0,0,0,...,2938,3965,181,0.0,10,0.0,0.0,0.0,0.0,0.0
Allende,874,184,1231,99,53.0,60,230,0,0,0,...,14358,27284,877,0.0,46,0.0,0.0,0.0,0.0,0.0
Anahuac,513,135,1226,42,15.0,37,135,0,0,0,...,9218,14525,494,0.0,27,0.0,0.0,0.0,0.0,0.0
Apodaca,13072,4128,812254,2836,886.0,727,3444,0,0,0,...,219581,403094,9977,0.0,688,0.0,0.0,0.0,0.0,0.0

In [14]:
NL_AYUN_2021.drop(['ID_ESTADO','ID_MUNICIPIO','SECCION','ID_CASILLA','EXT_CONTIGUA','UBICACION_CASILLA','TIPO_ACTA','SHA','FECHA_HORA_ACOPIO','FECHA_HORA_VERIFICACION','ORIGEN','DIGITALIZACION'

], axis = 1, inplace= True)

In [15]:
NL_AYUN_2021.head()

,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,TOTAL_REP_PARTIDO_CI_VOTARON,TOTAL_VOTOS_SACADOS,PAN,PRI,PRD,PT,PVEM,MC,...,CI_5,CI_6,CNR,Votos Anulados,TOTAL_VOTOS_ASENTADO,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,OBSERVACIONES,CONTABILIZADA
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,0,0,0,0,119,440,31,33,18,436,...,0,0,1,54,0.0,1734,2288,78,0.0,4
Agualeguas,0,0,0,0,1216,1074,0,0,1,601,...,0,0,1,33,0.0,2938,3965,181,0.0,10
Allende,0,0,0,0,4633,4764,0,431,90,2039,...,0,0,1,376,0.0,14358,27284,877,0.0,46
Anahuac,0,0,0,0,1582,3280,32,62,56,851,...,0,0,0,287,0.0,9218,14525,494,0.0,27
Apodaca,0,0,0,0,50330,69818,1480,5883,5958,10756,...,0,0,64,4059,0.0,219581,403094,9977,0.0,688

In [16]:
NL_AYUN_2021.to_csv('final_NL_AYUN_2021.csv')