In [2]:
import pandas as pd
import numpy as np

Alcaldes 2018

In [22]:
temp_content = pd.read_csv('NL_AYUN_2018.csv')

In [23]:
group = temp_content.groupby('MUNICIPIO')

In [24]:
NL_AYUN_2018 = group.sum()

In [25]:
NL_AYUN_2018.head()

,ID_ESTADO,ID_MUNICIPIO,SECCION,ID_CASILLA,EXT_CONTIGUA,UBICACION_CASILLA,TIPO_ACTA,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,TOTAL_REP_PARTIDO_CI_VOTARON,...,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,OBSERVACIONES,CONTABILIZADA,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,76,4,6,6,2.0,8,20,0,0,0,...,1734,2288,78,0.0,4,0.0,0.0,0.0,0.0,0.0
Agualeguas,190,20,66,11,1.0,19,50,0,0,0,...,2938,3965,181,0.0,10,0.0,0.0,0.0,0.0,0.0
Allende,874,184,1231,99,53.0,60,230,0,0,0,...,14358,27284,877,0.0,46,0.0,0.0,0.0,0.0,0.0
Anahuac,513,135,1226,42,15.0,37,135,0,0,0,...,9218,14525,494,0.0,27,0.0,0.0,0.0,0.0,0.0
Apodaca,13072,4128,812254,2836,886.0,727,3444,0,0,0,...,219581,403094,9977,0.0,688,0.0,0.0,0.0,0.0,0.0

In [26]:
NL_AYUN_2018.drop(['ID_ESTADO','ID_MUNICIPIO','SECCION','ID_CASILLA','EXT_CONTIGUA','UBICACION_CASILLA','TIPO_ACTA','SHA','FECHA_HORA_ACOPIO','FECHA_HORA_VERIFICACION','ORIGEN','DIGITALIZACION'

], axis = 1, inplace= True)

In [27]:
NL_AYUN_2018.head()

,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,TOTAL_REP_PARTIDO_CI_VOTARON,TOTAL_VOTOS_SACADOS,PAN,PRI,PRD,PT,PVEM,MC,...,CI_5,CI_6,CNR,Votos Anulados,TOTAL_VOTOS_ASENTADO,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,OBSERVACIONES,CONTABILIZADA
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,0,0,0,0,119,440,31,33,18,436,...,0,0,1,54,0.0,1734,2288,78,0.0,4
Agualeguas,0,0,0,0,1216,1074,0,0,1,601,...,0,0,1,33,0.0,2938,3965,181,0.0,10
Allende,0,0,0,0,4633,4764,0,431,90,2039,...,0,0,1,376,0.0,14358,27284,877,0.0,46
Anahuac,0,0,0,0,1582,3280,32,62,56,851,...,0,0,0,287,0.0,9218,14525,494,0.0,27
Apodaca,0,0,0,0,50330,69818,1480,5883,5958,10756,...,0,0,64,4059,0.0,219581,403094,9977,0.0,688

In [28]:
NL_AYUN_2018.to_csv('final_NL_AYUN_2018.csv')

Alcaldes 2021

In [29]:
temp_2021 = pd.read_csv('NL_AYUN_2021.csv')

In [30]:
group = temp_2021.groupby('MUNICIPIO')

In [31]:
NL_AYUN_2021 = group.sum()

In [32]:
NL_AYUN_2021.head()

,ID_ESTADO,ID_MUNICIPIO,SECCION,ID_CASILLA,EXT_CONTIGUA,UBICACION_CASILLA,TIPO_ACTA,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,TOTAL_REP_PARTIDO_CI_VOTARON,...,TOTAL_VOTOS_ASENTADO,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,CONTABILIZADA,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,76,4,6,4,0,8,16,0.0,0.0,0.0,...,0.0,2018,2512,48,4,0.0,0.0,0.0,0.0,0.0
Agualeguas,190,20,66,10,0,19,40,0.0,0.0,0.0,...,0.0,2866,4147,120,10,0.0,0.0,0.0,0.0,0.0
Allende,912,192,1283,81,0,63,192,0.0,0.0,0.0,...,0.0,13205,28919,576,48,0.0,0.0,0.0,0.0,0.0
Anahuac,532,140,1268,32,0,38,112,0.0,0.0,0.0,...,0.0,8964,14822,336,28,0.0,0.0,0.0,0.0,0.0
Apodaca,13965,4410,877485,1337,118,774,2940,58540.0,0.0,0.0,...,0.0,220494,440894,8820,735,0.0,0.0,0.0,0.0,0.0

In [33]:
NL_AYUN_2021.drop(['ID_ESTADO','ID_MUNICIPIO','SECCION','ID_CASILLA','EXT_CONTIGUA','UBICACION_CASILLA','TIPO_ACTA','SHA','FECHA_HORA_ACOPIO','FECHA_HORA_VERIFICACION','ORIGEN','DIGITALIZACION'

], axis = 1, inplace= True)

In [34]:
NL_AYUN_2021.head()

,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,TOTAL_REP_PARTIDO_CI_VOTARON,TOTAL_VOTOS_SACADOS,PAN,PRI,PRD,PVEM,PT,MC,...,C_PT_MORENA,C_PT_PANAL,C_MORENA_PANAL,NO_REGISTRADOS,NULOS,TOTAL_VOTOS_ASENTADO,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,CONTABILIZADA
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,0.0,0.0,0.0,0.0,544,31,0,514,123,426,...,0,0,0,0,21,0.0,2018,2512,48,4
Agualeguas,0.0,0.0,0.0,0.0,1795,128,4,2,0,806,...,0,0,0,0,47,0.0,2866,4147,120,10
Allende,0.0,0.0,0.0,0.0,3417,5947,28,145,124,1251,...,1,3,4,1,232,0.0,13205,28919,576,48
Anahuac,0.0,0.0,0.0,0.0,635,4775,0,51,0,91,...,0,0,0,1,229,0.0,8964,14822,336,28
Apodaca,58540.0,0.0,0.0,0.0,22136,141171,3525,1863,1722,21375,...,147,18,30,57,3336,0.0,220494,440894,8820,735

In [35]:
NL_AYUN_2021.to_csv('final_NL_AYUN_2021.csv')

Gobernador 2021

In [51]:
temp_NL_GOB_2021 = pd.read_csv('NL_GOB_2021.csv')

In [52]:
temp_NL_GOB_2021.head()

,CLAVE_CASILLA,CLAVE_ACTA,ID_ESTADO,ESTADO,ID_MUNICIPIO,MUNICIPIO,ID_DISTRITO_LOCAL,DISTRITO_LOCAL,SECCION,ID_CASILLA,...,OBSERVACIONES,CONTABILIZADA,MECANISMOS_TRASLADO,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_CAPTURA,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION,TIPO_DOCUMENTO
0,190001B0100,190001B01002,19,NUEVO LEON,1,Abasolo,20,DISTRITO 20,1,1,...,Por MAC,1,D,NaN,NaN,9/6/2021 9:33,NaN,NaN,NaN,-
1,190001C0100,190001C01002,19,NUEVO LEON,1,Abasolo,20,DISTRITO 20,1,1,...,Por MAC,1,D,NaN,NaN,9/6/2021 9:36,NaN,NaN,NaN,-
2,190002B0100,190002B01002,19,NUEVO LEON,1,Abasolo,20,DISTRITO 20,2,1,...,Por MAC,1,D,NaN,NaN,9/6/2021 9:39,NaN,NaN,NaN,-
3,190002C0100,190002C01002,19,NUEVO LEON,1,Abasolo,20,DISTRITO 20,2,1,...,Por MAC,1,D,NaN,NaN,9/6/2021 9:41,NaN,NaN,NaN,-
4,190003B0100,190003B01002,19,NUEVO LEON,2,Agualeguas,21,DISTRITO 21,3,1,...,Por MAC,1,D,NaN,NaN,9/6/2021 10:23,NaN,NaN,NaN,-

In [53]:
group = temp_NL_GOB_2021.groupby('MUNICIPIO')

In [54]:
NL_GOB_2021 = group.sum()

In [55]:
NL_GOB_2021.head()

,ID_ESTADO,ID_MUNICIPIO,ID_DISTRITO_LOCAL,SECCION,ID_CASILLA,EXT_CONTIGUA,UBICACION_CASILLA,TIPO_ACTA,TOTAL_BOLETAS_SOBRANTES,TOTAL_PERSONAS_VOTARON,...,TOTAL_VOTOS_ASENTADO,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,CONTABILIZADA,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,76,4,80,6,4,0,8,8,0.0,0.0,...,0.0,2014,2512,48,4,0.0,0.0,0.0,0.0,0.0
Agualeguas,190,20,210,66,10,0,19,20,0.0,0.0,...,0.0,2898,4147,120,10,0.0,0.0,0.0,0.0,0.0
Allende,912,192,1248,1283,81,0,63,96,0.0,0.0,...,0.0,13165,28919,576,48,0.0,0.0,0.0,0.0,0.0
Anahuac,532,140,588,1268,32,0,38,56,0.0,0.0,...,0.0,8860,14822,336,28,0.0,0.0,0.0,0.0,0.0
Apodaca,13965,4410,6589,877485,1337,118,774,1470,0.0,0.0,...,0.0,220895,440894,8820,735,0.0,0.0,0.0,0.0,0.0

In [60]:
NL_GOB_2021.drop(['ID_ESTADO','ID_MUNICIPIO','ID_DISTRITO_LOCAL','SECCION','ID_CASILLA','EXT_CONTIGUA','UBICACION_CASILLA','TIPO_ACTA','SHA','FECHA_HORA_ACOPIO','FECHA_HORA_VERIFICACION','ORIGEN','DIGITALIZACION'

], axis = 1, inplace= True)

KeyError: "['ID_ESTADO' 'ID_MUNICIPIO' 'SECCION' 'ID_CASILLA' 'EXT_CONTIGUA'\n 'UBICACION_CASILLA' 'TIPO_ACTA' 'SHA' 'FECHA_HORA_ACOPIO'\n 'FECHA_HORA_VERIFICACION' 'ORIGEN' 'DIGITALIZACION'] not found in axis"

In [57]:
NL_GOB_2021.drop(['TOTAL_BOLETAS_SOBRANTES','TOTAL_PERSONAS_VOTARON','TOTAL_REP_PARTIDO_CI_VOTARON','TOTAL_VOTOS_SACADOS',

], axis = 1, inplace= True)

In [44]:
NL_GOB_2021.head()

,ID_DISTRITO_LOCAL,PAN,PRI,PRD,PVEM,PT,MC,MORENA,PANAL,PES,...,C_PT_MORENA,C_PT_PANAL,C_MORENA_PANAL,NO_REGISTRADOS,NULOS,TOTAL_VOTOS_ASENTADO,TOTAL_VOTOS_CALCULADO,LISTA_NOMINAL,REPRESENTANTES_PP_CI,CONTABILIZADA
MUNICIPIO,,,,,,,,,,,,,,,,,,,,,
Abasolo,80,483,255,18,232,71,763,102,20,20,...,0,0,0,1,20,0.0,2014,2512,48,4
Agualeguas,210,1515,340,4,9,4,778,161,7,0,...,0,0,0,0,52,0.0,2898,4147,120,10
Allende,1248,2340,4810,51,141,156,4106,860,145,26,...,2,2,4,0,253,0.0,13165,28919,576,48
Anahuac,588,1325,3979,29,99,77,1900,1046,50,70,...,1,0,2,0,214,0.0,8860,14822,336,28
Apodaca,6589,39757,58969,873,1756,2031,86520,22626,985,859,...,147,13,40,74,3045,0.0,220895,440894,8820,735

In [45]:
NL_GOB_2021.to_csv('Final_NL_GOB_2021.csv')